create database client CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE client;

CREATE TABLE UTILISATEUR (
ID_U VARCHAR(20) PRIMARY KEY,
DATE_INS INT NOT NULL
);

create table inscription (
NOM VARCHAR(20) NOT NULL,
PRENOM VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20) NOT NULL, 
TELEPHONE INT NOT NULL,
SEXE VARCHAR(2) NOT NULL,
PRIMARY KEY (NOM, ID_U),
FOREIGN KEY(ID_U) REFERENCES UTILISATEUR(ID_U)
);

